(function(g){var window=this;'use strict';var S3=function(a){a.oa("cardstatechange",a.Nk()&&a.ip()?1:0)},T3=function(a,b){var c=g.Ya(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},Fkb=function(a){var b=g.ds(a);
a=g.gs(a);return new g.Tr(b.x,b.y,a.width,a.height)},Gkb=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.zC(a,b,function(){g.AC(e);c.apply(a,arguments)},d)},W3=function(a){a=g.bb(a);
delete U3[a];g.id(U3)&&V3&&V3.stop()},Ikb=function(){V3||(V3=new g.Cu(function(){Hkb()},20));
var a=V3;a.isActive()||a.start()},Hkb=function(){var a=g.gb();
g.Wc(U3,function(b){Jkb(b,a)});
g.id(U3)||Ikb()},X3=function(a,b,c,d){g.Wu.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},Jkb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;Kkb(a,a.progress);1==a.progress?(a.j=0,W3(a),a.onFinish(),a.Br()):a.isPlaying()&&a.AL()},Kkb=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},Lkb=function(a,b){g.yb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},Y3=function(a,b,c,d,e){X3.call(this,b,c,d,e);
this.element=a},Mkb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
Y3.call(this,a,b,c,d,e)},Nkb=function(a){return Math.pow(a,3)},Okb=function(a){return 3*a*a-2*a*a*a},Pkb=function(a){g.I.call(this);
this.B=a||window;this.j=[]},Z3=function(a){return a.baseUrl||null},$3=function(a,b){return g.$s(g.nr(a,b),function(c){return!!c})},Qkb=function(a,b,c){function d(ra){var na=ra.hovercardButton;
if(!na)return null;na=na.subscribeButtonRenderer;if(!na)return null;var ta=f(na.unsubscribedButtonText),ca=f(na.subscribedButtonText);if(na.subscribed){var U=f(na.subscriberCountWithUnsubscribeText);var Ma=f(na.subscriberCountText)}else U=f(na.subscriberCountText),Ma=f(na.subscriberCountWithSubscribeText);var y=null;if(ra.signinEndpoint){y=T3(ra,"signinEndpoint","webNavigationEndpointData","url");if(!y){var Z,Ua;y=null==(Ua=g.R(null==(Z=na.signInEndpoint)?void 0:Z.commandMetadata,g.J2))?void 0:Ua.url}if(!y)return null}return ta&&
(ca||y)?{subscribed:na.subscribed,subscribeText:ta,subscribeCount:U,unsubscribeText:ca,unsubscribeCount:Ma,enabled:na.enabled,signinUrl:y,classic:ra.useClassicSubscribeButton}:null}
function e(ra){if(ra){var na=[],ta=ra.videoId;ta&&na.push("v="+ta);(ta=ra.playlistId)&&na.push("list="+ta);(ra=ra.startTimeSeconds)&&na.push("t="+ra);return"/watch?"+na.join("&")}}
function f(ra){if(!ra)return null;var na=ra.simpleText;return na?na:ra.runs?g.nr(ra.runs,function(ta){return ta.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,u=null,x=!1,B=null,F=null,H=null,G=null,M=null,Q=null;if("VIDEO"===h)g.R(l,g.kG)?m=g.R(l,g.kG).url:(Q=g.R(l,g.lT),m=e(Q)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.R(l,g.kG)?m=g.R(l,g.kG).url:(Q=g.R(l,g.lT),m=e(Q)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(x=T3(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;q="new";(x=!!b.isSubscribe)?B=d(b):F=f(b.subscribersText)}else"WEBSITE"===h?((H=T3(l,"urlEndpoint","url"))&&(m=H),n=!0,q="new",H=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(M=f(b.additionalFeesText)),(n=T3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=T3(b,"title","accessibility","accessibilityData","label");var S=b.endpoint?b.endpoint.clickTrackingParams:null,
la="";if(b.metadata){var qa=f(b.metadata);qa&&(la=qa)}return{id:"element-"+c,type:h,title:f(b.title),metadata:la,callToAction:f(b.callToAction),SV:b.image,iconUrl:H,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,hE:p,playlistLength:t,channelId:u,subscribeButton:B,subscribersText:F,isSubscribe:x,targetUrl:m||null,G7:n,sessionData:S?{itct:S}:null,cca:q,KC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:$3(b.impressionUrls||[],Z3),u7:$3(b.hovercardShowUrls||[],Z3),clickUrls:$3(l.loggingUrls||[],Z3),visualElement:g.oF(b.trackingParams),productPrice:G,additionalFeesText:M,watchEndpoint:Q||null}},Rkb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:$3(a.impressionUrls||[],Z3),elements:$3(a.elements||[],function(d,e){return Qkb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.oF(a.trackingParams));return c},Skb=function(a){g.CV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.cS(a)||g.eS(a);this.events=new g.LK(this);g.J(this,this.events);this.events.T(this.player,g.WJ("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.XJ("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Jb);this.events.T(window,"focus",this.paa);this.load();var b=g.bf("STYLE");(g.Me("HEAD")[0]||document.body).appendChild(b);this.addOnDisposeCallback(function(){g.of(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Tkb=function(a){return a.player.getVideoData().If?"current":a.Z?"new":"current"},a4=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},Ukb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Rkb(f,Tkb(a))));b4(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.jy;d&&(c.postParams={ad_tracking:d});if(b=g.rSa(b))if(b=g.Hn(b),b=g.Yd(b))a.C=g.RB(b,c)},b4=function(a,b,c){c=void 0===c?!0:c;
a.player.jf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.v(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&Vkb(a);c=[];d=new g.VJ(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.T({I:"div",S:"ytp-ce-shadow"}),g.sU(a.player,a.B.element,4),a.D=new g.xG(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Wkb(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.sU(a.player,f.element,4);var h=new g.VJ(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Xkb(a,f,e)}else g.uF(new g.QC("buildEndscreenElement null",
e))}a.player.sf(c);a.Jb()}},Vkb=function(a){var b=g.pF(),c=g.qF();
c&&b&&a.endscreen.visualElement&&g.zB(g.EF)(void 0,c,b,a.endscreen.visualElement)},Wkb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ma:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.KC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:c4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:d4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-video-title","ytp-webkit-ellipsis"],W:{dir:g.av(b.title||"")},ya:b.title},{I:"div",S:b.hE?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
ya:b.videoDuration||void 0}]}]};c=new g.T(a);break;case "PLAYLIST":a={I:"div",Ma:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.KC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:c4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:d4(a,b.targetUrl),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],W:{dir:g.av(b.title||"")},ya:b.title},{I:"div",S:"ytp-ce-playlist-count",
V:[{I:"div",S:"ytp-ce-playlist-icon"},{I:"div",S:"ytp-ce-playlist-count-text",ya:b.playlistLength||void 0}]}]}]};c=new g.T(a);break;case "CHANNEL":c={I:"div",Ma:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.KC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ma:["ytp-ce-channel-title","ytp-ce-link"],W:{href:d4(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.av(b.title||"")},ya:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",ya:b.subscribersText}:"",b.metadata?{I:"div",Ma:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],ya:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:c4(b)}]};c=new g.T(c);var d=g.Ne(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Ku(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.kW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player,!1);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ma:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.KC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",W:{dir:g.av(b.title||"")},ya:b.title},{I:"div",S:"ytp-ce-website-metadata",ya:b.metadata},{I:"a",Ma:["ytp-ce-website-goto","ytp-ce-link"],W:{href:d4(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:c4(b)},{I:"div",S:"ytp-ce-expanding-icon",W:Ykb(b.iconUrl)}]};c=new g.T(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",ya:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",ya:b.additionalFeesText})),a={I:"div",Ma:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.KC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",W:{dir:g.av(b.title||"")},ya:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",ya:b.metadata},{I:"a",Ma:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:d4(a,b.targetUrl),target:"_blank",tabindex:"-1"},ya:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:c4(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
ya:b.callToAction||void 0}]}]},c=new g.T(a)}b.isPlaceholder&&g.Ku(c.element,"ytp-ce-placeholder");return c},c4=function(a){if(a.SV)var b=a.SV.thumbnails;
return Ykb(b?b[b.length-1].url:null)},Ykb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Xkb=function(a,b,c){function d(m){m&&(b.Qa("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.Ku(b.element,"ytp-ce-force-expand"),e4(a,c.id,!0)):(g.Mu(b.element,"ytp-ce-force-expand"),g.Mu(b.element,"ytp-ce-element-hover"),e4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Qa("mouseenter",function(){Zkb(a,b,c)});
b.Qa("mouseleave",function(){$kb(a,b,c)});
a.player.U().B||b.Qa("click",function(){g.Ku(b.element,"ytp-ce-element-hover")});
b.Qa("click",function(m){alb(a,c,m)});
b.Qa("keypress",function(m){alb(a,c,m)});
b.Qa("focus",function(){Zkb(a,b,c)});
b.Qa("blur",function(){$kb(a,b,c)});
b.Qa("touchstart",function(){Zkb(a,b,c)});
var l=g.Pe("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.Mu(b.element,"ytp-ce-element-hover");g.Mu(b.element,"ytp-ce-force-expand")});
b.Qa("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.Pe("ytp-sb-subscribe",b.element));d(g.Pe("ytp-sb-unsubscribe",b.element));b.Qa("focus",f);b.Qa("blur",h)},alb=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Ju(d,"ytp-ce-element");){g.Ju(d,"subscribe-label")&&blb(a,b);
if(g.Ju(d,"ytp-ce-channel-subscribe"))return;d=g.pf(d)}if(!d||g.Ju(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])$kb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.cca)blb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Hn(d4(a,b.targetUrl)),g.ZG(g.Yd(c),void 0,b.sessionData);else{var e=g.oS(a.player.U())||a.player.getVideoData().If,f=function(){var h=d4(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.EB(h);e&&n&&(n.v||
n.list)?a.player.Jo(n.v,l,n.list,!1,void 0,m||void 0):g.Lwa(h,l)};
blb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},d4=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.vS(a)+b}else return"";return b},Zkb=function(a,b,c){g.Ju(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.Ku(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.Cu(function(){g.Ku(b.element,"ytp-ce-element-hover")},200)).start():g.Ku(b.element,"ytp-ce-element-hover"),f4(a,c.u7),e4(a,c.id,!0))},$kb=function(a,b,c){g.Mu(b.element,"ytp-ce-element-hover");
g.Mu(b.element,"ytp-ce-force-expand");e4(a,c.id,!1)},e4=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.v(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Ou(a.j[e].element,"ytp-ce-element-shadow-show",c)},f4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||a4(a))c&&c();else{b=clb(a,b);var e=0,f=!1,h=new g.Cu(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.jE(b[a],d)}},blb=function(a,b,c){f4(a,b.clickUrls,c);
(a=g.qF())&&b.G7&&g.LF(a,b.visualElement)},clb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(dlb(b[d],c));return a},dlb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},elb=function(a){return"string"===typeof a?a:""},g4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},flb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},h4=function(a){return a.value?a.value:null},i4=function(a){if(!a)return null;
var b=g.Hn(elb(a.value));b=g.Yd(b);if(!b)return null;var c=g4(a.target,glb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new flb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},hlb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},klb=function(a){if(!a)return null;
var b=g4(a.type,ilb),c=g4(a.trigger,jlb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=i4(a?a:null);return b?new hlb(b,c,a):null},llb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},mlb=function(a,b){return g.Db(a.action,b)},nlb=function(a,b){this.context=a;
this.j=b},olb=function(a){return a.customMessage?j4("div","iv-card-message",a.customMessage):""},k4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",W:{style:a},V:c}},plb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.v(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(j4("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},j4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.av(c);return{I:a,W:b,ya:c}},qlb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.VC&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.VC+");");c.dir=g.av(a.customMessage);var d=[{I:"span",ya:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ma:b,W:c,V:d}},l4=function(a,b,c,d){if(d){b=g.v(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.dj.click,5)}},rlb=function(a,b){this.merchant=a;
this.price=b},slb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},tlb=function(a,b){return b?b:slb(a)?"current":"new"},m4=function(a,b){g.I.call(this);
var c=this;this.element=a;this.context=b;this.rb=!1;this.Xa=new Map;this.Za=new Map;this.context.J.addEventListener(g.WJ("annotations_module"),function(d){(d=c.Xa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.XJ("annotations_module"),function(d){(d=c.Za.get(d))&&d.apply(c)})},n4=function(a,b,c,d,e,f,h){a.context.j.Qa(b,"click",function(l){a.BL(c,d,e,f||[],h||0,l)});
a.context.j.Qa(b,"touchstart",function(){a.rb=!1});
a.context.j.Qa(b,"touchmove",function(){a.rb=!0})},ulb=function(a){var b;
return(null==(b=g.R(a,g.kG))?0:b.url)?g.R(a,g.kG).url:(a=g.R(a,g.lT))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},o4=function(a,b,c){return{sX:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
P_:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
UK:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},vlb=function(a,b,c){m4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Gb=this.Na=this.Pb=this.C=this.isInitialized=!1;this.cards=[];this.tb=this.Z=this.La=this.G=this.Va=this.j=null;this.ma=[];this.qa=this.N=this.Gf=this.Ia=null;this.K=0;this.Ga=new g.Cu(function(){},c.X.Oi?4E3:3E3);
g.J(this,this.Ga);this.gb=new g.Cu(function(){});
g.J(this,this.gb);this.Aa=new nlb(c,function(e,f,h,l,m,n){n4(d,e,f,h,l,m,n)});
this.Y=new g.T({I:"div",S:"iv-drawer",W:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",W:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ma:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.J(this,this.Y);this.D=this.Y.element;this.fb=new g.xG(this.Y,330);g.J(this,this.fb);this.Tb=g.Pe("iv-drawer-header-text",this.D);this.B=g.Pe("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Pb&&p4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Pb=d.C)&&q4(d)});
this.Sa=new g.LK(this);g.J(this,this.Sa);this.J.addEventListener("videodatachange",this.At.bind(this))},wlb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){p4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){q4(a)});
var c=b.headerText;g.rf(a.Tb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ia=g.oF(b.trackingParams);a.N=g.oF(b.closeTrackingParams);a.Gf=g.oF(b.iconTrackingParams)},xlb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.jb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.ZF(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,dj:{},jp:null,Mj:e.trackingParams?g.oF(e.trackingParams):null,Gf:f&&f.trackingParams?g.oF(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
VC:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};r4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.ZF(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:s4(a,c,b,f),sponsored:!1,dj:o4(f,e,f.command),jp:f.trackingParams?g.oF(f.trackingParams):null,Mj:e.trackingParams?g.oF(e.trackingParams):null,Gf:l&&l.trackingParams?g.oF(l.trackingParams):null,imageUrl:t4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.ZF(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,VC:null,title:f.title?g.ZF(f.title):"",customMessage:f.callToAction?g.ZF(f.callToAction):"",url:g.R(f.command,g.kG).url?i4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.R(f.command,g.kG).url}):null,onClickCommand:null};r4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.ZF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:s4(a,c,b,e),sponsored:!1,dj:o4(e,f,e.endpoint),jp:e.trackingParams?g.oF(e.trackingParams):null,Mj:f.trackingParams?g.oF(f.trackingParams):null,Gf:l&&l.trackingParams?g.oF(l.trackingParams):null,channelId:g.R(e.endpoint,g.QU).browseId,customMessage:e.customText?g.ZF(e.customText):null,profileImageUrl:t4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.ZF(e.channelName):"",metaInfo:[e.subscriberCountText?g.ZF(e.subscriberCountText):""],url:i4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.R(e.endpoint,g.QU).canonicalBaseUrl?g.R(e.endpoint,g.QU).canonicalBaseUrl:"/channel/"+g.R(e.endpoint,g.QU).browseId}),onClickCommand:null};r4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.ZF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:s4(a,c,b,e),sponsored:!1,dj:o4(e,f,e.action),jp:e.trackingParams?g.oF(e.trackingParams):null,Mj:f.trackingParams?g.oF(f.trackingParams):null,Gf:l&&l.trackingParams?g.oF(l.trackingParams):null,WF:t4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.ZF(e.customMessage):null,playlistVideoCount:g.ZF(e.playlistVideoCount),title:e.playlistTitle?g.ZF(e.playlistTitle):"",metaInfo:[e.channelName?g.ZF(e.channelName):
"",e.videoCountText?g.ZF(e.videoCountText):""],url:i4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:ulb(e.action)}),onClickCommand:null};r4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.ZF(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:s4(a,c,b,e),sponsored:!1,dj:o4(e,f,e.action),jp:e.trackingParams?g.oF(e.trackingParams):null,Mj:f.trackingParams?g.oF(f.trackingParams):null,Gf:l&&l.trackingParams?g.oF(l.trackingParams):null,WF:t4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.ZF(e.lengthString):null,customMessage:e.customMessage?g.ZF(e.customMessage):null,title:e.videoTitle?g.ZF(e.videoTitle):"",metaInfo:[e.channelName?g.ZF(e.channelName):
"",e.viewCountText?g.ZF(e.viewCountText):""],isLiveNow:!!e.badge,url:i4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:ulb(e.action)}),onClickCommand:null};r4(a,b)}}}}}a.K++},t4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},s4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},zlb=function(a,b){if(b=ylb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.gg.id),g.of(b.UM),g.Hb(a.cards,b),a.WG(),u4(a)},p4=function(a,b,c){if(!a.C){a.fb.show();
a.Va=new g.Cu(function(){g.Ku(a.context.J.getRootNode(),g.WY.IV_DRAWER_OPEN)},0);
a.Va.start();a.Sa.T(a.B,"mousewheel",function(h){a.Ga.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.qF();d&&a.Ia&&a.N&&g.JF(d,[a.Ia,a.N]);b={TRIGGER_TYPE:b};for(var e=g.v(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.hY||(f.hY=!0,Alb(a.context.logger,f.gg.dj.sX,b)),d&&g.JF(d,[f.gg.jp]);S3(a.J);c&&(a.G=new g.Cu(function(){a.La=a.Z;a.tb.focus()},330),a.G.start())}},q4=function(a){a.C&&(a.fb.hide(),g.FC(a.Sa),g.Mu(a.context.J.getRootNode(),g.WY.IV_DRAWER_OPEN),a.C=!1,S3(a.J),a.G&&a.G.stop(),a.G=new g.Cu(function(){a.La&&(a.La.focus(),a.La=null)},330),a.G.start())},Clb=function(a){g.Lu(a.Ab(),
[g.WY.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.sU(a.J,a.D,5);Blb(a);a.Z=g.Pe("ytp-cards-button",a.J.getRootNode());a.tb=g.Pe("iv-drawer-close-button",a.D);a.isInitialized=!0},Blb=function(a){var b=g.Pe("iv-drawer-close-button",a.D);
a.context.j.Qa(b,"click",a.i5,a);a.context.j.Qa(a.B,"touchend",function(){a.Ga.start()});
a.context.j.Qa(a.B,"scroll",a.E5,a);a.context.B.subscribe("onHideControls",function(){a.Na=!0});
a.context.B.subscribe("onShowControls",function(){a.Na=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Na=g.Ju(a.J.getRootNode(),"ytp-autohide")});
a.ma.push(g.xE("iv-button-shown",a.Y7,a));a.ma.push(g.xE("iv-button-hidden",a.X7,a));Dlb(a)},Dlb=function(a){a.ma.push(g.xE("iv-teaser-shown",a.L1,a));
a.ma.push(g.xE("iv-teaser-hidden",a.Z7,a));a.ma.push(g.xE("iv-teaser-clicked",a.K1,a));a.Gb=!0},Elb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.R(b.onClickCommand,g.fhb))?void 0:c.targetId)?(a.qa=b,!0):!1},Flb=function(a,b){a.qa=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.QQa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.R(h[0],g.UZa))?void 0:d.timeRangeStartMillis)||0,a.qa=null,!0}return!1},r4=function(a,b){if(!Elb(a,b)||Flb(a,b)){var c=Glb(a,b);
if(c){var d={gg:b,UM:c.element,hY:!1};if(b.onClickCommand)a.J.L("web_infocards_teaser_show_logging_fix")&&(a.Gb||Dlb(a),zlb(a,b.id),c=Hlb(a,d),g.Nb(a.cards,c,0,d));else{a.isInitialized||Clb(a);zlb(a,b.id);var e=Hlb(a,d);g.Nb(a.cards,e,0,d);c.Da(a.B,e);a.WG()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,u4(a),Ilb(a,d),p4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&Jlb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){Jlb(a,
d)}),u4(a))}}},Glb=function(a,b){switch(b.type){case "simple":a=a.Aa;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",ya:b.displayDomain}:void 0;var d=qlb(b);c={I:"div",Ma:["iv-card"],V:[{I:"a",S:"iv-click-target",W:{href:b.url?h4(b.url)||"":""},V:[k4(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[j4("h2",void 0,b.title),d]}]}]};c=new g.T(c);l4(a,g.Oe("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Aa;c={I:"div",Ma:["iv-card","iv-card-channel"],V:[{I:"a",Ma:["iv-click-target"],W:{href:h4(b.url)||"","data-ytid":b.channelId},V:[k4(b.profileImageUrl),
{I:"div",S:"iv-card-content",V:[olb(b),{I:"h2",S:"iv-card-primary-link",ya:b.title},plb(b)]}]}]};c=new g.T(c);l4(a,g.Oe("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Aa;c={I:"div",Ma:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",W:{href:h4(b.url)||""},V:[k4(b.WF,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",ya:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[olb(b),j4("h2","iv-card-primary-link",b.title),plb(b)]}]}]};
c=new g.T(c);l4(a,g.Oe("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Aa;var e=0!=b.offers.length;c=["iv-card"];d="";var f=qlb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",ya:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",ya:f.merchant}),f={I:"div",V:e});e=b.url?h4(b.url)||"":"";c={I:"div",Ma:c,W:{tabindex:"0"},V:[{I:"a",Ma:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",ya:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",W:{href:e},V:[j4("h2",d,b.title),f]}]}]};c=new g.T(c);d=g.bf("span");g.rf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.je(d,"adInfo");l4(a,g.Oe("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Aa;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",ya:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ma:["yt-badge","yt-badge-live"],ya:"LIVE NOW"}:null;e={I:"div",Ma:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",W:{href:(null==(c=b.url)?void 0:h4(c))||""},V:[k4(b.WF,d),{I:"div",S:"iv-card-content",V:[olb(b),j4("h2","iv-card-primary-link",b.title),plb(b),f]}]}]};c=new g.T(e);l4(a,g.Oe("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},Hlb=function(a,b){if(0===a.cards.length)return 0;
a=g.Eb(a.cards,function(c){return b.gg.startMs>c.gg.startMs||b.gg.startMs===c.gg.startMs&&b.gg.timestamp>=c.gg.timestamp?!0:!1});
return-1===a?0:a+1},Klb=function(a){if(a.j)return"productListing"===a.j.gg.type;
if(a.J.L("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.or(a.cards,function(c){return"productListing"===c.gg.type})}return g.or(a.cards,function(c){return"productListing"===c.gg.type})},u4=function(a){g.Ou(a.J.getRootNode(),"ytp-cards-shopping-active",Klb(a))},Jlb=function(a,b){if(!g.Ju(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.qF(),d=a.j?a.j.gg.Gf:a.Gf;
c&&d&&g.KF(c,[d]);a.j=b;u4(a)}(c=a.isInitialized&&"none"==a.Ab().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.gg.teaserDurationMs&&a.J.tB(!0,{teaserText:b.gg.teaserText,durationMs:b.gg.teaserDurationMs,onClickCommand:b.gg.onClickCommand});a.gb.isActive()||((!a.C||!a.Ga.isActive()&&a.Na)&&Ilb(a,b),a.gb.start(910+b.gg.teaserDurationMs))}},Ilb=function(a,b){a.Y.Db?(b=new X3([0,
a.B.scrollTop],[0,b.UM.offsetTop],600,Okb),a.context.C.Qa(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.Qa(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.VF(a.Y,!0),a.B.scrollTop=b.UM.offsetTop,g.VF(a.Y,!1))},v4=function(a){return a.j&&a.j.gg?a.j.gg:a.cards[0]&&a.cards[0].gg?a.cards[0].gg:null},ylb=function(a,b){return g.Db(a.cards,function(c){return c.gg.id===b})},w4=function(a,b,c){m4.call(this,a,b);
this.annotation=c;this.isActive=!1},Llb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},x4=function(a,b,c){w4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},Mlb=function(a,b){var c=void 0===c?0:c;
var d=Fkb(b).width;g.bs(b,d);c=new Mkb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Nkb);g.J(a,c);a.context.C.Qa(c,"begin",function(){g.hs(b,!0)});
c.play()},Plb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ma:["iv-branding-context-name"],ya:b.channel_name}),d=a.createElement({I:"div",Ma:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.kW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J,!1),a.j.Da(d));var f=a.createElement({I:"div",Ma:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ma:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.hs(h,!1);var l=a.createElement({I:"div",Ma:["branding-context-container-outer"]});l.appendChild(h);g.Wr(l,"right",b.image_width+"px");g.lf(a.Ab(),l);a.C=new g.Cu(function(){Nlb(a,h,l)},500);
g.J(a,a.C);a.context.j.Qa(a.Ab(),"mouseover",function(){Olb(a,h,l,f,b.image_height)});
a.context.j.Qa(a.Ab(),"mouseout",function(){a.C.start()})}},Olb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.gs(b);a.j||(b.style.width=g.as(f.width,!0),c.style.width=g.as(f.width,!0));g.Wr(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Wr(d,"right","1px");a.D=!0;g.hs(b,!0);a.G=new g.Cu(function(){g.Ku(this.Ab(),"iv-branding-active")},0,a);
a.G.start()}},Nlb=function(a,b,c){g.Mu(a.Ab(),"iv-branding-active");
a.K=new g.Cu(function(){g.hs(b,!1);a.j||(c.style.width=g.as(0,!0))},250);
a.K.start();a.D=!1},Qlb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.X=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},Rlb=function(a,b,c){w4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ma:["iv-promo-contents"]});this.G=new g.Cu(function(){d.j.setAttribute("aria-hidden","true");g.hs(d.C,!1);g.hs(d.B,!0)},700,this);
g.J(this,this.G)},Ulb=function(a,b,c){c.stopPropagation();
Slb(a);Tlb(a,b);a.j.focus()},Vlb=function(a){a.isCollapsed||a.Z||a.D||(g.Ku(a.Ab(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},Slb=function(a){a.G.stop();
a.isCollapsed&&(g.Nu(a.Ab(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.hs(a.B,!1),g.hs(a.C,!0))},Tlb=function(a,b){a.D||(a.D=g.ag(function(){Wlb(this);
Vlb(this)},b,a))},Wlb=function(a){a.D&&(g.Qa.clearTimeout(a.D),a.D=null)},Xlb=function(a){this.J=a},Alb=function(a,b,c){b&&(c?y4(a,b.map(function(d){return g.qu(d,c)})):y4(a,b))},y4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.v(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.jE(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},Ylb=function(a){g.CV.call(this,a);
var b=this;this.Y=this.N=!1;this.loadNumber=0;this.K={};this.logger=new Xlb(this.player);this.D=new g.LK(this);this.G=this.Ax=null;this.events=new g.LK(this);this.Wg=this.Z=this.j=null;this.ma=[];g.J(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.oa("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.oa("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.oa("onShowControls")});
this.D.T(this.player,"resize",function(d){b.oa("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.oa("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.M1,this);this.subscribe("resize",this.GJ,this);this.player.U().La.subscribe("vast_info_card_add",this.qZ,this);g.J(this,this.events);this.qa=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.T({I:"div",Ma:["ytp-player-content","ytp-iv-player-content"]});g.J(this,this.B);g.sU(this.player,this.B.element,4);this.B.hide();this.C=new g.T({I:"div",Ma:["ytp-iv-video-content"]});g.J(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.qa);this.C.element.appendChild(a);this.xu()&&this.load();var c=this.createElement({I:"style"});(g.Me("HEAD")[0]||document.body).appendChild(c);this.addOnDisposeCallback(function(){g.of(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Zlb=function(a){a=a.createElement({I:"div",
Ma:["annotation","annotation-type-custom"]});g.hs(a,!1);return a},$lb=function(a,b){b=!b.isCued()&&!g.EG(b,1024);
g.VF(a.B,b);g.VF(a.C,b)},amb=function(a,b,c){a.N=!0;
a.G=g.RB(b,c)},bmb=function(a,b){for(var c={},d=g.v(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.$a(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(bmb(a,e))}return c},fmb=function(a){var b=a.player.getVideoData();
if(b.Va){var c=a.player.U().La.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.LB(h)&&h.responseXML?h.responseXML:null)&&cmb(a,h)}};
g.YC()&&(d.onFinish=dmb(a,d.onFinish));d.postParams={ic_only:"1"};emb(d,c);a.N=!0;g.RB(b.Va,d)}}},emb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.bH&&(a.postParams.ic_coll=b.bH);b.VM&&(a.postParams.ic_xml=b.VM);b.aL&&(a.postParams.ic_track=b.aL)},gmb=function(a){var b=new g.T({I:"div"});
g.hs(b.element,!1);var c=new vlb(a.player,b.element,z4(a));g.J(c,b);b.Da(a.B.element);c.KF();return c},imb=function(a,b){var c,d;
if(b=null==(c=b.getWatchNextResponse())?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.Y=!0,hmb(a,b),b.headerText&&a.Wg&&(c=g.ZF(b.headerText),a.Wg.setAttribute("title",c))},z4=function(a){if(!a.Z){var b=new Pkb(a);
g.J(a,b);var c=new g.ap(a);g.J(a,c);a.Z=new Qlb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.sj)}return a.Z},cmb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.qF();if(e){var f=g.pF();f&&g.zB(g.lva)(void 0,e,f,[g.oF(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=bmb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=g4(f.type,jmb),p=g4(f.style,kmb),q=elb(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=klb;if(null==t)var u=null;else if(g.Ya(t)){l=[];for(var x=g.v(t),B=x.next();!B.done;B=x.next()){var F=f(B.value);
F&&l.push(F)}u=l}else{var H=f(t);u=H?[H]:[]}e=m&&n?new llb(m,n,p,u,r):null}else e=null}catch(qa){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var G=Zlb(f),M=null;switch(l.type){case "branding":if(f.player.U().Ae)break;f.B.element.appendChild(G);M=new x4(G,z4(f),l);break;case "promotion":g.sU(f.player,G,4),M=new Rlb(G,z4(f),l)}M&&M.KF();if(f=M)g.J(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=gmb(a),g.J(a,a.j));if("card"===e.type){c=a.j;var Q=e&&e.data&&e.data.card_type;
f=e.data;if(Q)switch(l=f.tracking||{},l={sX:l.impression,click:l.click,close:l.close,P_:l.teaser_impression,UK:l.teaser_click},G=f.tracking_params||{},M=null,Q){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,dj:l,jp:G.card?g.oF(G.card):null,Mj:G.teaser?g.oF(G.teaser):null,Gf:G.icon?g.oF(G.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:i4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};r4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,dj:l,jp:G.card?g.oF(G.card):null,
Mj:G.teaser?g.oF(G.teaser):null,Gf:G.icon?g.oF(G.icon):null,WF:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:i4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};r4(c,e);break;case "productListing":f.signin_url&&(M=i4({target:"current",value:f.signin_url}));Q=[];for(var S=f.offers||[],la=0;la<S.length;la++)Q.push(new rlb(g.we(S[la].merchant),g.we(S[la].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,dj:l,jp:G.card?g.oF(G.card):null,Mj:G.teaser?g.oF(G.teaser):null,Gf:G.icon?g.oF(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,VC:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:i4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Qkb:M,Pkb:f.signin_title?f.signin_title:void 0,Okb:f.signin_message?f.signin_message:void 0,offers:Q,onClickCommand:null};r4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,dj:l,jp:G.card?g.oF(G.card):
null,Mj:G.teaser?g.oF(G.teaser):null,Gf:G.icon?g.oF(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,VC:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:i4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};r4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,dj:l,jp:G.card?g.oF(G.card):null,Mj:G.teaser?g.oF(G.teaser):null,Gf:G.icon?g.oF(G.icon):null,WF:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:i4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},r4(c,e)}}else wlb(a.j,e);c=!0}}c&&
(S3(a.player),a.GJ())},hmb=function(a,b){var c=!1;
a.j||(a.j=gmb(a),g.J(a,a.j));for(var d=g.v(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(xlb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.GT(f)||(c=a.j,d=b.headerText?g.ZF(b.headerText):"",g.rf(c.Tb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ia=b.trackingParams?g.oF(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.oF(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Gf=b.icon.infoCardIconRenderer.trackingParams?g.oF(b.icon.infoCardIconRenderer.trackingParams):null,a.GJ());S3(a.player)}},lmb=function(a,b,c,d,e){if(!a.player.U().Ae){var f=[];
b.navigationEndpoint&&g.R(b.navigationEndpoint,g.QU)&&g.R(b.navigationEndpoint,g.QU).browseId&&f.push(new hlb("openUrl","click",new flb("/channel/"+g.R(b.navigationEndpoint,g.QU).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.R(b.subscribeButton,
g.zT)){d.channel_id=g.R(b.subscribeButton,g.zT).channelId;var l;b=g.R(b.subscribeButton,g.zT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.ZF(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.ZF(b.subscriberCountText))):(b.subscriberCountText&&(e=g.ZF(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.ZF(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.R(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.J2))?void 0:m.url)||"";l={subscribeText:g.ZF(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.ZF(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new llb(c,"branding","branding",f,d);l=Zlb(a);a.B.element.appendChild(l);f=new x4(l,z4(a),f);f.KF();g.J(f,f);a.K[c]=f}},dmb=function(a,b){return function(){var c=g.Ia.apply(0,arguments);
a.isDisposed()||a.ma.push(g.uu.Qi(function(){b.apply(null,g.ma(c))}))}},mmb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.kU.prototype.tB=g.ba(29,function(a,b){var c=g.SV(this.zb());c&&c.tB(a,b)});
var U3={},V3=null;g.ib(X3,g.Wu);g.k=X3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;W3(this);this.startTime=a=g.gb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.xJ();this.im("play");this.isPaused()&&this.im("resume");this.j=1;var b=g.bb(this);b in U3||(U3[b]=this);Ikb();Jkb(this,a);return!0};
g.k.stop=function(a){W3(this);this.j=0;a&&(this.progress=1);Kkb(this,this.progress);this.im("stop");this.Br()};
g.k.pause=function(){this.isPlaying()&&(W3(this),this.j=-1,this.im("pause"))};
g.k.xa=function(){0==this.j||this.stop(!1);this.im("destroy");X3.Nf.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.AL=function(){this.im("animate")};
g.k.im=function(a){this.dispatchEvent(new Lkb(a,this))};
g.ib(Lkb,g.yb);g.ib(Y3,X3);Y3.prototype.C=function(){};
Y3.prototype.AL=function(){this.C();Y3.Nf.AL.call(this)};
Y3.prototype.Br=function(){this.C();Y3.Nf.Br.call(this)};
Y3.prototype.xJ=function(){this.C();Y3.Nf.xJ.call(this)};
g.ib(Mkb,Y3);Mkb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(Pkb,g.I);g.k=Pkb.prototype;g.k.Qa=function(a,b,c,d){c=(0,g.eb)(c,d||this.B);a=g.zC(a,b,c);this.j.push(a);return a};
g.k.XI=function(a,b,c,d){c=(0,g.eb)(c,d||this.B);a=Gkb(a,b,c);this.j.push(a);return a};
g.k.Lc=function(a){g.AC(a);g.Hb(this.j,a)};
g.k.Lf=function(){g.AC(this.j);this.j.length=0};
g.k.xa=function(){this.Lf();g.I.prototype.xa.call(this)};g.w(Skb,g.CV);g.k=Skb.prototype;g.k.load=function(){g.CV.prototype.load.call(this);if(!a4(this)){var a=g.sSa(this.player.getVideoData());a?(a=Rkb(a,Tkb(this)),b4(this,a,!1)):Ukb(this)}};
g.k.unload=function(){b4(this,null);this.C&&(this.C.abort(),this.C=null);g.CV.prototype.unload.call(this)};
g.k.Jh=function(a,b){return a4(this)?"loadCustomEndscreenRenderer"===a?(a=Rkb(b,"new"),b4(this,a),!0):null:null};
g.k.getOptions=function(){return a4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Jb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<nmb.length;f++){var h=Math.abs(b.width-nmb[f]);if(-1===e||d>=h)e=f,d=h}d=omb[e];this.B&&g.Wr(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.fs(e.element,m,f);g.bs(e.element,n,p);g.Nu(e.element,pmb);256<m||256<f?g.Ku(e.element,"ytp-ce-large-round"):96<m||96<f?g.Ku(e.element,"ytp-ce-medium-round"):g.Ku(e.element,"ytp-ce-small-round");g.Nu(e.element,qmb);m=h.left+h.width/2;h=h.top+l/2;g.Ku(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Nu(e.element,omb);g.Ku(e.element,d);(e=g.Ne(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Wr(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())f4(this,this.endscreen.impressionUrls),(a=g.qF())&&this.endscreen.visualElement&&g.IF(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.Ku(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Ku(b,"ytp-ce-shown");f4(this,c.impressionUrls);(b=g.qF())&&g.IF(b,c.visualElement);this.player.U().K&&this.player.kb("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.Mu(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Mu(b,"ytp-ce-shown");this.player.U().K&&this.player.kb("endscreenelementhidden",a)}};
g.k.paa=function(a){var b=this;a.target===window&&(new g.Cu(function(){for(var c=g.v(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Nu(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var nmb=[346,426,470,506,570,640,853,1280,1920],omb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),qmb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],pmb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var glb={Msa:"current",bTa:"new"};var ilb={CLOSE:"close",EWa:"openUrl",SUBSCRIBE:"subscribe"},jlb={dra:"click",CLOSE:"close",nEa:"hidden",T0a:"rollOut",U0a:"rollOver",E2a:"shown"};llb.prototype.cf=function(){var a=mlb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var kmb={Tla:"anchored",b1:"branding",CHANNEL:"channel",Csa:"cta",qEa:"highlightText",rIa:"label",PLAYLIST:"playlist",lZa:"popup",C5a:"speech",SUBSCRIBE:"subscribe",l9a:"title",VIDEO:"video",Kfb:"website"},jmb={b1:"branding",Roa:"card",Qua:"drawer",pEa:"highlight",BOa:"marker",O_a:"promotion",TEXT:"text",phb:"widget"};g.w(m4,g.I);g.k=m4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.VJ(a,b,{id:c,namespace:"annotations_module"});d&&this.Xa.set(a,d);e&&this.Za.set(a,e);this.context.J.sf([a])};
g.k.KF=function(){this.context.B.subscribe("resize",this.WG,this)};
g.k.Ab=function(){return this.element};
g.k.BL=function(a,b,c,d,e,f){if(this.rb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.of(this.Ab())};
g.k.WG=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=h4(a);if(f){var h=tlb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.If||!1,n=g.EB(f||"");m&&n&&(n.v||n.list)?e.context.J.Jo(n.v,b,n.list,!1):g.ZG(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);y4(this.context.logger,c,l,d);slb(f)||(c=g.qF(),d=b.itct,c&&d&&g.LF(c,g.oF(d)))}};
g.k.xa=function(){this.Xa.clear();this.Za.clear();g.I.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.T(a);g.J(this,a);return a.element};g.w(vlb,m4);g.k=vlb.prototype;g.k.At=function(){this.qa&&r4(this,this.qa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.gs(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.WG=function(){var a=this.isAvailable();g.hs(this.Ab(),a);g.Ou(this.context.J.getRootNode(),g.WY.IV_DRAWER_ENABLED,a);S3(this.J)};
g.k.destroy=function(){this.J.tB(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.yE(this.ma);g.FC(this.Sa);this.Va&&this.Va.dispose();this.G&&this.G.dispose();m4.prototype.destroy.call(this)};
g.k.i5=function(){if(this.C){y4(this.context.logger,v4(this).dj.close);var a=g.qF();a&&this.N&&g.LF(a,this.N);q4(this)}};
g.k.E5=function(){g.Ou(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.Y7=function(){var a=g.qF(),b=v4(this);b=b?b.Gf:this.Gf;a&&b&&g.JF(a,[b])};
g.k.X7=function(){var a=g.qF(),b=v4(this);b=b?b.Gf:this.Gf;a&&b&&g.KF(a,[b])};
g.k.L1=function(){var a=v4(this);y4(this.context.logger,a.dj.P_);var b=g.qF();if(b&&a)if(this.J.L("web_infocards_teaser_show_logging_fix")){var c=[];a.Mj&&c.push(a.Mj);a.Gf&&c.push(a.Gf);0<c.length&&g.JF(b,c)}else g.JF(b,[a.Mj,a.Gf])};
g.k.Z7=function(){var a=g.qF(),b=v4(this);a&&b&&g.KF(a,[b.Mj])};
g.k.K1=function(a){var b=v4(this),c=g.qF();this.j?a?(a=this.context.logger,y4(a,b.dj.UK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Mj&&g.LF(c,b.Mj)):(a=this.context.logger,y4(a,b.dj.UK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Gf&&g.LF(c,b.Gf)):(a=this.context.logger,y4(a,b.dj.UK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Gf&&g.LF(c,this.Gf))};g.w(w4,m4);w4.prototype.KF=function(){m4.prototype.KF.call(this);Llb(this)};
w4.prototype.show=function(){m4.prototype.show.call(this);var a=g.qF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.JF(a,[g.oF(b.itct)])};
w4.prototype.hide=function(){m4.prototype.hide.call(this);var a=g.qF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.KF(a,[g.oF(b.itct)])};g.w(x4,w4);x4.prototype.kB=function(){g.Ku(this.Ab(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ma:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.hs(this.B,!1);var b=this.createElement({I:"button",Ma:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Ab().appendChild(b);var c=this.annotation.cf();c&&n4(this,b,c,this.annotation.id,a.session_data);Plb(this,a)};
x4.prototype.show=function(){if(!this.isActive&&(w4.prototype.show.call(this),this.N||(this.kB(),this.N=!0),g.hs(this.Ab(),!0),this.isActive=!0,this.B)){try{Mlb(this,this.B)}catch(a){}g.Ku(this.context.J.getRootNode(),"ytp-branding-shown")}};
x4.prototype.hide=function(){this.isActive&&(w4.prototype.hide.call(this),g.hs(this.Ab(),!1),this.isActive=!1,g.Mu(this.context.J.getRootNode(),"ytp-branding-shown"))};
x4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);w4.prototype.destroy.call(this)};g.w(Rlb,w4);g.k=Rlb.prototype;
g.k.kB=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Ab().setAttribute("aria-hidden","true");this.Ab().setAttribute("aria-label","Promotion");this.Ab().tabIndex=0;var e=this.annotation.cf(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ma:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",ya:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",ya:b.playlist_length.toString()}),h.appendChild(f));e&&n4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Kn(f,h4(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",ya:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",ya:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ma:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ma:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",ya:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&n4(this,
this.Ab(),e,this.annotation.id,b.session_data,void 0,c)}g.Ku(this.j,"iv-click-target");e&&n4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",ya:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",ya:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ma:["yt-badge","iv-promo-badge-live"],ya:"LIVE NOW"})),g.Ku(this.j,"iv-click-target"),e&&n4(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ma:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.Qa(this.B,"click",function(q){Ulb(a,5E3,q)});
c.appendChild(this.B);g.hs(this.B,!1);this.context.j.Qa(this.Ab(),"mouseover",this.V6,this);this.context.j.Qa(this.Ab(),"mouseout",this.U6,this);this.context.j.Qa(this.Ab(),"touchend",function(q){Ulb(a,5E3,q)});
this.C=this.createElement({I:"button",Ma:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.Qa(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.Q6:this.P6,this);c.appendChild(this.C);g.Lu(this.Ab(),d);h&&(g.lf(this.Ab(),h),n&&h.appendChild(n));g.lf(this.Ab(),this.N);g.lf(this.Ab(),c)};
g.k.show=function(){this.isActive||(w4.prototype.show.call(this),this.Y||(this.kB(),this.Y=!0),g.hs(this.Ab(),!0),g.ag(function(){g.Mu(this.Ab(),"iv-promo-inactive")},100,this),this.Ab().removeAttribute("aria-hidden"),this.isActive=!0,Wlb(this),Slb(this),Tlb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.Ku(this.Ab(),"iv-promo-inactive"),this.isActive=!1,this.Ab().setAttribute("aria-hidden","true"))};
g.k.BL=function(a,b,c,d,e,f){return this.isCollapsed?!1:w4.prototype.BL.call(this,a,b,c,d,e,f)};
g.k.V6=function(a){this.Z=!0;Ulb(this,500,a)};
g.k.U6=function(){this.Z=!1;Vlb(this)};
g.k.P6=function(a){a.stopPropagation();this.hide()};
g.k.Q6=function(a){a.stopPropagation();Wlb(this);this.isCollapsed=!0;g.Ku(this.Ab(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();w4.prototype.destroy.call(this)};g.w(Ylb,g.CV);g.k=Ylb.prototype;g.k.Jh=function(a,b){if(!mmb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.p2(b))&&cmb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(zlb(this.j,b),S3(this.player)),!0}return null};
g.k.getOptions=function(){return mmb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.xu=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return g.ST(b)||g.dU(this.player.app)?!1:1===c&&!b.JU||a.La.get(b.videoId)||g.HT(b)||g.tSa(b)?!0:!1};
g.k.GJ=function(){if(this.C){var a=this.player.ob().getVideoContentRect(!0);g.fs(this.C.element,a.width,a.height);g.bs(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Wk();a=this.j;b=b.width;g.Ou(a.D,"iv-drawer-small",426>=b);g.Ou(a.D,"iv-drawer-big",1280<=b)}};
g.k.M1=function(a){$lb(this,a.state);g.EG(a.state,2)&&(this.Nk()&&this.ip()&&2!==this.player.getPresentingPlayerType()&&this.uB(!1),this.tB(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.LB(h)&&h.responseXML?h.responseXML:null)&&(cmb(b,h),g.Ku(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.CV.prototype.load.call(this);$lb(this,this.player.Rb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.YC()&&(a=dmb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().La.get(d);f&&emb(e,f);f=f&&(f.VM||f.bH);if(!c.Fx||f)c.Va?amb(this,c.Va,e):(this.Ax=function(){if(!b.N)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.GT(h))&&!b.Y&&imb(b,h)},this.player.addEventListener("videodatachange",this.Ax));
g.sU(this.player,this.C.element,4);this.GJ();(f=g.HT(c))&&hmb(this,f);(f=g.tSa(c))&&f.featuredChannel&&lmb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.Wg=g.Pe("ytp-cards-button",this.player.getRootNode());g.GT(c)&&imb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Va&&amb(this,b.Va,a)};
g.k.unload=function(){this.player.jf("annotations_module");for(var a=g.v(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.Z=null;this.j&&(this.j.destroy(),this.j=null,S3(this.player));this.N=!1;this.G&&(this.G.abort(),this.G=null);this.Y=!1;this.K={};this.B.hide();g.CV.prototype.unload.call(this);this.C.detach();this.Ax&&(this.player.removeEventListener("videodatachange",this.Ax),this.Ax=null)};
g.k.qZ=function(a){a===this.player.getVideoData().videoId&&(this.loaded?fmb(this):this.load())};
g.k.Nk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.Y};
g.k.ip=function(){return!!this.j&&this.j.C};
g.k.uB=function(a,b,c){b=void 0===b?!1:b;this.Nk();this.j&&(a?c?p4(this.j,c,b):p4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):q4(this.j))};
g.k.tB=function(a,b){this.player.oa(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.U().La.unsubscribe("vast_info_card_add",this.qZ,this);g.Mu(this.player.getRootNode(),g.WY.IV_DRAWER_OPEN);for(var a=this.ma,b=g.uu,c=0,d=a.length;c<d;c++)b.Rj(a[c]);this.ma.length=0;g.CV.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.T(a);g.J(this,a);return a.element};g.BV("annotations_module",Ylb);g.BV("creatorendscreen",Skb);})(_yt_player);
