(function(g){var window=this;'use strict';var xqb=function(a,b){a.kb("onAutonavCoundownStarted",b)},e6=function(a,b,c){g.Ou(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Rg(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.MS&&(b.lengthText?(e=b.lengthText||null,f=b.uw||null):b.lengthSeconds&&(e=g.OG(b.lengthSeconds),f=g.OG(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.MQa(d).type;var l=b instanceof g.MS?b.isLivePlayback:null,m=b instanceof g.MS?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],t=[];n&&r.push(n);p&&(r.push(p),t.push(p));q&&t.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.bK("Watch $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Xk(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:t.join(" \u2022 "),autoplayAlternativeHeader:b.Ds};b instanceof g.LS&&(c.playlist_length=b.playlistLength);a.update(c)},f6=function(a){var b=a.U(),c=b.D;
g.T.call(this,{I:"a",S:"ytp-autonav-suggestion-card",W:{href:"{{url}}",target:c?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",Ma:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],W:{style:"{{background}}"},V:[{I:"div",W:{"aria-label":"{{timestamp}}"},Ma:["ytp-autonav-timestamp"],ya:"{{duration}}"},{I:"div",Ma:["ytp-autonav-live-stamp"],ya:"Live"},{I:"div",
Ma:["ytp-autonav-upcoming-stamp"],ya:"Upcoming"},{I:"div",S:"ytp-autonav-list-overlay",V:[{I:"div",S:"ytp-autonav-mix-text",ya:"Mix"},{I:"div",S:"ytp-autonav-mix-icon"}]}]},{I:"div",Ma:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],ya:"{{title}}"},{I:"div",Ma:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],ya:"{{author}}"},{I:"div",Ma:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],ya:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.j=c;this.Qa("click",this.onClick);this.Qa("keypress",this.onKeyPress)},g6=function(a,b){b=void 0===b?!1:b;
g.T.call(this,{I:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.N=b;this.G=this.K=void 0;this.C=0;this.container=new g.T({I:"div",S:"ytp-autonav-endscreen-countdown-container"});g.J(this,this.container);this.container.Da(this.element);b=a.U();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.T({I:"div",S:"ytp-autonav-endscreen-upnext-container",W:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-header"},{I:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",ya:"{{autoplayAlternativeHeader}}"},{I:"a",S:"ytp-autonav-endscreen-link-container",W:{href:"{{url}}",target:d?b.Y:""},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",W:{style:"{{background}}"},V:[{I:"div",W:{"aria-label":"{{timestamp}}"},Ma:["ytp-autonav-timestamp"],
ya:"{{duration}}"},{I:"div",Ma:["ytp-autonav-live-stamp"],ya:"Live"},{I:"div",Ma:["ytp-autonav-upcoming-stamp"],ya:"Upcoming"}]},{I:"div",S:"ytp-autonav-endscreen-video-info",V:[{I:"div",S:"ytp-autonav-endscreen-premium-badge"},{I:"div",S:"ytp-autonav-endscreen-upnext-title",ya:"{{title}}"},{I:"div",S:"ytp-autonav-endscreen-upnext-author",ya:"{{author}}"},{I:"div",S:"ytp-autonav-view-and-date",ya:"{{views_and_publish_time}}"},{I:"div",S:"ytp-autonav-author-and-view",ya:"{{author_and_views}}"}]}]}]});
g.J(this,this.j);this.j.Da(this.container.element);d||this.T(this.j.Fa("ytp-autonav-endscreen-link-container"),"click",this.XS);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.j.Fa("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.T({I:"div",S:"ytp-autonav-overlay"});g.J(this,this.overlay);this.overlay.Da(this.container.element);this.B=new g.T({I:"div",S:"ytp-autonav-endscreen-button-container"});g.J(this,this.B);this.B.Da(this.container.element);
this.cancelButton=new g.T({I:"button",Ma:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],W:{"aria-label":"Cancel autoplay"},ya:"Cancel"});g.J(this,this.cancelButton);this.cancelButton.Da(this.B.element);this.cancelButton.Qa("click",this.T1,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.T({I:"a",Ma:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],W:{href:"{{url}}",role:"button","aria-label":"Play next video"},ya:"Play Now"});g.J(this,this.playButton);this.playButton.Da(this.B.element);this.playButton.Qa("click",this.XS,this);this.J.L("web_player_autonav_next_button_renderer")?(this.J.createServerVe(this.playButton.element,this.playButton,!0),(b=this.J.getVideoData())&&yqb(this,b)):this.J.createClientVe(this.playButton.element,this,115130);this.D=new g.Cu(function(){zqb(c)},
500);
g.J(this,this.D);this.WS();this.T(a,"autonavvisibility",this.WS);this.J.L("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.S1),this.T(a,"onAutonavCoundownStarted",this.S8))},h6=function(a){var b=a.J.Wk(!0,a.J.isFullscreen());
g.Ou(a.container.element,"ytp-autonav-endscreen-small-mode",a.Jf(b));g.Ou(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.MK);g.Ou(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.xf());g.Ou(a.J.getRootNode(),"countdown-running",a.bl());g.Ou(a.container.element,"ytp-player-content",a.J.xf());g.Wr(a.overlay.element,{width:b.width+"px"});if(!a.bl()){a.J.xf()?Aqb(a,Math.round(Bqb(a)/1E3)):Aqb(a);b=!!a.suggestion&&!!a.suggestion.Ds;var c=a.J.xf()||!b;
g.Ou(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.Ou(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.VF(a.B,a.J.xf());g.Ou(a.element,"ytp-enable-w2w-color-transitions",Cqb(a))}},zqb=function(a){var b=Bqb(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);Aqb(a,Math.ceil((b-c)/1E3));500>=b-c&&a.bl()?a.select(!0):a.bl()&&a.D.start()},Bqb=function(a){if(a.J.isFullscreen()){var b;
a=null==(b=a.J.getVideoData())?void 0:b.WB;return-1===a||void 0===a?8E3:a}return 0<=a.J.Ws()?a.J.Ws():g.pJ(a.J.U().experiments,"autoplay_time")||1E4},yqb=function(a,b){a.J.L("web_player_autonav_next_button_renderer");
b=b.z5;a.K=null==b?void 0:b.navigationEndpoint;b=null==b?void 0:b.trackingParams;a.playButton&&b&&a.J.setTrackingParams(a.playButton.element,b)},Cqb=function(a){var b;
return!(null==(b=a.J.getVideoData())||!b.watchToWatchTransitionRenderer)},Aqb=function(a,b){b=void 0===b?-1:b;
a=a.j.Fa("ytp-autonav-endscreen-upnext-header");g.mf(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.cf("Up next in $SECONDS".slice(0,d)));var e=g.bf("span");g.Iu(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.rf(e,b);a.appendChild(e);a.appendChild(g.cf("Up next in $SECONDS".slice(d+c.length)));return}}g.rf(a,"Up next")},i6=function(a,b){g.T.call(this,{I:"div",
Ma:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},j6=function(a){g.T.call(this,{I:"div",
Ma:["ytp-upnext","ytp-player-content"],W:{"aria-label":"{{aria_label}}"},V:[{I:"div",S:"ytp-cued-thumbnail-overlay-image",W:{style:"{{background}}"}},{I:"span",S:"ytp-upnext-top",V:[{I:"span",S:"ytp-upnext-header",ya:"Up Next"},{I:"span",S:"ytp-upnext-title",ya:"{{title}}"},{I:"span",S:"ytp-upnext-author",ya:"{{author}}"}]},{I:"a",S:"ytp-upnext-autoplay-icon",W:{role:"button",href:"{{url}}","aria-label":"Play next video"},V:[{I:"svg",W:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
V:[{I:"circle",S:"ytp-svg-autoplay-circle",W:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",S:"ytp-svg-autoplay-ring",W:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",S:"ytp-svg-fill",W:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",S:"ytp-upnext-bottom",V:[{I:"span",S:"ytp-upnext-cancel"},{I:"span",S:"ytp-upnext-paused",
ya:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.G=this.Fa("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.Cu(this.hH,5E3,this);this.B=0;var b=this.Fa("ytp-upnext-cancel");this.cancelButton=new g.T({I:"button",Ma:["ytp-upnext-cancel-button","ytp-button"],W:{tabindex:"0","aria-label":"Cancel autoplay"},ya:"Cancel"});g.J(this,this.cancelButton);this.cancelButton.Qa("click",this.U1,this);this.cancelButton.Da(b);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.J(this,this.D);this.api.createClientVe(this.element,this,18788);b=this.Fa("ytp-upnext-autoplay-icon");this.T(b,"click",this.V1);this.api.createClientVe(b,this,115130);this.YS();this.T(a,"autonavvisibility",this.YS);this.T(a,"mdxnowautoplaying",this.D9);this.T(a,"mdxautoplaycanceled",this.E9);g.Ou(this.element,"ytp-upnext-mobile",this.api.U().B)},Dqb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.WB;return-1===a||void 0===a?8E3:a}return 0<=a.api.Ws()?a.api.Ws():g.pJ(a.api.U().experiments,"autoplay_time")||1E4},Eqb=function(a,b){b=Dqb(a,b);
var c=Math,d=c.min;var e=(0,g.qD)()-a.B;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.bl()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.bl()&&a.j.start()},k6=function(a){i6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.T({I:"div",S:"ytp-suggestion-panel",V:[{I:"div",Ma:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],ya:"More videos"}]});this.N=new g.T({I:"div",S:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new g6(this.player);g.J(this,this.B);this.B.Da(this.element);a.getVideoData().Qf?this.j=this.B:(this.j=new j6(a),g.sU(this.player,this.j.element,4),g.J(this,this.j));this.overlay=new g.T({I:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.J(this,this.overlay);this.overlay.Da(this.element);this.D=new g.LK(this);g.J(this,this.D);g.J(this,this.table);this.table.Da(this.element);this.table.show();g.J(this,this.N);this.N.Da(this.table.element);this.hide()},l6=function(a){var b=a.xf();
b!==a.G&&(a.G=b,a.player.oa("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},m6=function(a,b){g.T.call(this,{I:"button",
Ma:["ytp-watch-on-youtube-button","ytp-button"],ya:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.t_();2===this.buttonType&&g.Ku(this.element,"ytp-continue-watching-button");this.Qa("click",this.onClick);this.Qa("videodatachange",this.t_);g.VF(this,!0)},n6=function(a,b){i6.call(this,a,"embeds-lite-endscreen");
this.J=a;this.od=b;this.J.createClientVe(this.element,this,156943);this.watchButton=new m6(a,2);g.J(this,this.watchButton);this.watchButton.Da(this.element);this.hide()},Fqb=function(a){i6.call(this,a,"subscribecard-endscreen");
this.j=new g.T({I:"div",S:"ytp-subscribe-card",V:[{I:"img",S:"ytp-author-image",W:{src:"{{profilePicture}}"}},{I:"div",S:"ytp-subscribe-card-right",V:[{I:"div",S:"ytp-author-name",ya:"{{author}}"},{I:"div",S:"html5-subscribe-button-container"}]}]});g.J(this,this.j);this.j.Da(this.element);var b=a.getVideoData();this.subscribeButton=new g.kW("Subscribe",null,"Unsubscribe",null,!0,!1,b.Kl,b.subscribed,"trailer-endscreen",null,a,!1);g.J(this,this.subscribeButton);this.subscribeButton.Da(this.j.Fa("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ra);this.Ra();this.hide()},o6=function(a){var b=a.U(),c=g.IK||g.WR?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.T.call(this,{I:"a",Ma:e,W:{href:"{{url}}",target:d?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{I:"div",S:"ytp-videowall-still-image",W:{style:"{{background}}"}},{I:"span",S:"ytp-videowall-still-info",W:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-info-bg",V:[{I:"span",S:"ytp-videowall-still-info-content",W:c,V:[{I:"span",S:"ytp-videowall-still-info-title",ya:"{{title}}"},
{I:"span",S:"ytp-videowall-still-info-author",ya:"{{author_and_views}}"},{I:"span",S:"ytp-videowall-still-info-live",ya:"Live"},{I:"span",S:"ytp-videowall-still-info-duration",ya:"{{duration}}"}]}]}]},{I:"span",Ma:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",S:"ytp-videowall-still-listlabel-length",V:[" (",{I:"span",ya:"{{playlist_length}}"},")"]}]},{I:"span",Ma:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",S:"ytp-videowall-still-listlabel-length",ya:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.LK(this);g.J(this,this.j);this.Qa("click",this.onClick);this.Qa("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.createServerVe(this.element,this);this.onVideoDataChange()},p6=function(a){i6.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.N=!1;this.Y=null;this.B=new g.LK(this);g.J(this,this.B);this.K=new g.Cu(function(){g.Ku(b.element,"ytp-show-tiles")},0);
g.J(this,this.K);var c=new g.T({I:"button",Ma:["ytp-button","ytp-endscreen-previous"],W:{"aria-label":"Previous"},V:[g.aG()]});g.J(this,c);c.Da(this.element);c.Qa("click",this.Z1,this);this.table=new g.SF({I:"div",S:"ytp-endscreen-content"});g.J(this,this.table);this.table.Da(this.element);c=new g.T({I:"button",Ma:["ytp-button","ytp-endscreen-next"],W:{"aria-label":"Next"},V:[g.bG()]});g.J(this,c);c.Da(this.element);c.Qa("click",this.Y1,this);a.getVideoData().Qf?this.j=new g6(a,!0):this.j=new j6(a);
g.J(this,this.j);g.sU(this.player,this.j.element,4);a.createClientVe(this.element,this,158789);this.hide()},q6=function(a){return g.tU(a.player)&&a.RC()&&!a.D},r6=function(a){var b=a.xf();
b!==a.N&&(a.N=b,a.player.oa("autonavvisibility"))},s6=function(a){i6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new m6(a,1);g.J(this,this.watchButton);this.watchButton.Da(this.element);g.Teb(a)&&(this.j=new g.r2(a),g.J(this,this.j),this.B=new g.T({I:"div",Ma:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],W:{tabIndex:"-1"},V:[this.j]}),g.J(this,this.B),this.j.Da(this.B.element),this.B.Da(this.element));a.createClientVe(this.element,this,156914);this.hide()},Jqb=function(a){g.CV.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.LK(this);g.J(this,this.listeners);var c=a.U(),d=a.getVideoData();d=d&&0!==d.limitedPlaybackDurationInSeconds;g.qC(g.gS(c))&&d&&!g.oU(a)?(this.B=!0,this.endScreen=new n6(a,g.fU(a))):g.pU(a)?this.endScreen=new s6(a):Gqb(a)?(this.D=!0,Hqb(this),this.j?this.endScreen=new k6(a):this.endScreen=new p6(a)):c.lh?this.endScreen=new Fqb(a):this.endScreen=new i6(a);g.J(this,this.endScreen);g.sU(a,this.endScreen.element,4);Iqb(this);
this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.WJ("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.XJ("endscreen"),function(e){b.onCueRangeExit(e)})},Hqb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Ml&&a.C===b.Qf)return!1;a.j=b.Ml;a.C=b.Qf;return!0},Gqb=function(a){a=a.U();
return a.Xd&&!a.lh},Iqb=function(a){a.player.jf("endscreen");
var b=a.player.getVideoData();b=new g.VJ(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.VJ(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.sf([b,c])};
g.kU.prototype.Ws=g.ba(16,function(){return this.app.Ws()});
g.Q0.prototype.Ws=g.ba(15,function(){return this.getVideoData().FU});
g.gU.prototype.Fm=g.ba(14,function(a){this.oh().Fm(a)});
g.LW.prototype.Fm=g.ba(13,function(a){this.j!==a&&(this.j=a,this.Ra())});
g.XX.prototype.Fm=g.ba(12,function(a){this.overflowButton&&this.overflowButton.Fm(a)});
g.gU.prototype.Gm=g.ba(11,function(a){this.oh().Gm(a)});
g.QW.prototype.Gm=g.ba(10,function(a){this.j!==a&&(this.j=a,this.Ra())});
g.XX.prototype.Gm=g.ba(9,function(a){this.shareButton&&this.shareButton.Gm(a)});
g.gU.prototype.uu=g.ba(8,function(a){this.oh().uu(a)});
g.cW.prototype.uu=g.ba(7,function(a){this.EQ!==a&&(this.EQ=a,this.uq())});
g.gU.prototype.Pr=g.ba(6,function(a){this.oh().Pr(a)});
g.XX.prototype.Pr=g.ba(5,function(a){this.DQ!==a&&(this.DQ=a,this.Gk())});g.w(f6,g.T);f6.prototype.select=function(){this.J.Jo(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.lD||void 0)&&this.J.logClick(this.element)};
f6.prototype.onClick=function(a){g.LU(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
f6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};g.w(g6,g.T);g.k=g6.prototype;g.k.qG=function(a){this.suggestion!==a&&(this.suggestion=a,e6(this.j,a),this.playButton.updateValue("url",this.suggestion.Xk()),h6(this))};
g.k.bl=function(){return 0<this.C};
g.k.DB=function(){this.bl()||(this.C=Date.now(),zqb(this),xqb(this.J,Bqb(this)),g.Ou(this.J.getRootNode(),"countdown-running",this.bl()))};
g.k.Sw=function(){this.lq();zqb(this);var a=this.j.Fa("ytp-autonav-endscreen-upnext-header");a&&g.rf(a,"Up next")};
g.k.lq=function(){this.bl()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,void 0===a?!1:a);this.lq()};
g.k.XS=function(a){g.LU(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):a.currentTarget===this.j.Fa("ytp-autonav-endscreen-link-container")&&(a=this.j.Fa("ytp-autonav-endscreen-link-container"),this.J.logVisibility(a,!0),this.J.logClick(a)),this.J.L("web_player_autonav_next_button_renderer")&&this.K?(this.J.kb("innertubeCommand",this.K),this.lq()):this.select())};
g.k.T1=function(){this.J.logClick(this.cancelButton.element);g.mU(this.J,!0);this.G&&this.J.kb("innertubeCommand",this.G)};
g.k.onVideoDataChange=function(a,b){this.J.L("web_player_autonav_next_button_renderer")&&yqb(this,b);var c;this.G=null==(c=b.X4)?void 0:c.command};
g.k.S8=function(a){if(Cqb(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.WG(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.WG(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.WG(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.WG(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.WG(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.WG(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.Ou(this.element,"ytp-w2w-animate",!0)}};
g.k.S1=function(a){this.J.L("web_autonav_color_transition")&&2!==a&&g.Ou(this.element,"ytp-w2w-animate",!1)};
g.k.WS=function(){var a=this.J.xf();this.N&&this.Db!==a&&g.VF(this,a);h6(this);this.J.logVisibility(this.container.element,a);this.J.logVisibility(this.cancelButton.element,a);this.J.logVisibility(this.j.Fa("ytp-autonav-endscreen-link-container"),a);this.J.logVisibility(this.playButton.element,a)};
g.k.Jf=function(a){return 400>a.width||459>a.height};g.w(i6,g.T);g.k=i6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.RC=function(){return!1};
g.k.xf=function(){return!1};
g.k.JX=function(){return!1};g.w(j6,g.T);g.k=j6.prototype;g.k.hH=function(){this.notification&&(this.D.stop(),this.Lc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.qG=function(a){this.suggestion=a;e6(this,a,"hqdefault.jpg")};
g.k.YS=function(){g.VF(this,this.api.xf());this.api.logVisibility(this.element,this.api.xf());this.api.logVisibility(this.Fa("ytp-upnext-autoplay-icon"),this.api.xf());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.xf())};
g.k.M9=function(){window.focus();this.hH()};
g.k.DB=function(a){var b=this;this.bl()||(g.zE("a11y-announce","Up Next "+this.suggestion.title),this.B=(0,g.qD)(),this.j=new g.Cu(function(){Eqb(b,a)},25),Eqb(this,a),xqb(this.api,Dqb(this,a)));
g.Mu(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.T.prototype.hide.call(this)};
g.k.bl=function(){return!!this.j};
g.k.Sw=function(){this.lq();this.B=(0,g.qD)();Eqb(this);g.Ku(this.element,"ytp-upnext-autoplay-paused")};
g.k.lq=function(){this.bl()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.U().L("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.hH(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Rg()}),this.C=this.T(this.notification,"click",this.M9),this.D.start())}this.lq();this.api.nextVideo(!1,a)};
g.k.V1=function(a){!g.qf(this.cancelButton.element,a.target)&&g.LU(a,this.api)&&(this.api.xf()&&this.api.logClick(this.Fa("ytp-upnext-autoplay-icon")),this.select())};
g.k.U1=function(){this.api.xf()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.mU(this.api,!0)};
g.k.D9=function(a){this.api.getPresentingPlayerType();this.show();this.DB(a)};
g.k.E9=function(){this.api.getPresentingPlayerType();this.lq();this.hide()};
g.k.xa=function(){this.lq();this.hH();g.T.prototype.xa.call(this)};g.w(k6,i6);g.k=k6.prototype;g.k.create=function(){i6.prototype.create.call(this);this.D.T(this.player,"appresize",this.eC);this.D.T(this.player,"onVideoAreaChange",this.eC);this.D.T(this.player,"videodatachange",this.onVideoDataChange);this.D.T(this.player,"autonavchange",this.ZS);this.D.T(this.player,"onAutonavCancelled",this.W1);this.onVideoDataChange()};
g.k.show=function(){i6.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.mU(this.player,!1);g.tU(this.player)&&this.RC()&&!this.C?(l6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.DB():3===this.videoData.autonavState&&this.j.Sw()):(g.mU(this.player,!0),l6(this));this.eC()};
g.k.hide=function(){i6.prototype.hide.call(this);this.j.Sw();l6(this)};
g.k.eC=function(){var a=this.player.Wk(!0,this.player.isFullscreen());l6(this);h6(this.B);g.Ou(this.element,"ytp-autonav-cancelled-small-mode",this.Jf(a));g.Ou(this.element,"ytp-autonav-cancelled-tiny-mode",this.OI(a));g.Ou(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.Wr(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.Ou(this.videos[a].element,"ytp-suggestion-card-with-margin",1===a%2)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.L("web_player_autonav_empty_suggestions_fix")){var b=g.mT(this.videoData);b&&(this.j.qG(b),this.j!==this.B&&this.B.qG(b))}if(a&&a.length)for(b=0;b<Kqb.length;++b){var c=Kqb[b];if(a&&a[c]){this.videos[b]=new f6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,e6(d,c));g.J(this,this.videos[b]);this.videos[b].Da(this.N.element)}}this.eC()}};
g.k.ZS=function(a){1===a?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.lq(),this.Db&&this.eC()):(this.K=!0,this.xf()&&(2===a?this.j.DB():3===a&&this.j.Sw()))};
g.k.W1=function(a){a?this.ZS(1):(this.C=null,this.K=!1)};
g.k.RC=function(){return 1!==this.videoData.autonavState};
g.k.Jf=function(a){return(910>a.width||459>a.height)&&!this.OI(a)&&!(400>=a.width||360>=a.height)};
g.k.OI=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.xf=function(){return this.Db&&g.tU(this.player)&&this.RC()&&!this.C};
var Kqb=[1,3,2,4];g.w(m6,g.T);g.k=m6.prototype;g.k.t_=function(){switch(this.buttonType){case 1:var a="Watch again on YouTube";var b=156915;break;case 2:a="Continue watching on YouTube";b=156942;break;default:a="Continue watching on YouTube",b=156942}this.update({content:a});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,b)};
g.k.onClick=function(a){this.J.L("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.MU(this.getVideoUrl(),this.J,a);this.J.L("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.U();if(g.YR(b)||g.fS(b)){var c={};g.YR(b)&&g.$T(this.J,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.wP(c,b);a=g.Ml(a,c)}return a};
g.k.logVisibility=function(){this.J.logVisibility(this.element,this.Db&&this.Z)};
g.k.show=function(){g.T.prototype.show.call(this);this.logVisibility()};
g.k.hide=function(){g.T.prototype.hide.call(this);this.logVisibility()};
g.k.ac=function(a){g.T.prototype.ac.call(this,a);this.logVisibility()};g.w(n6,i6);n6.prototype.show=function(){3!==this.player.getPlayerState()&&(i6.prototype.show.call(this),this.od.Pr(!0),this.od.Gm(!0),this.J.U().Qd||this.od.Fm(!0),this.J.logVisibility(this.element,!0),this.watchButton.ac(!0))};
n6.prototype.hide=function(){i6.prototype.hide.call(this);this.od.Pr(!1);this.od.Gm(!1);this.od.Fm(!1);this.J.logVisibility(this.element,!1);this.watchButton.ac(!1)};g.w(Fqb,i6);Fqb.prototype.Ra=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Kl;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.w(o6,g.T);o6.prototype.select=function(){this.api.Jo(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.lD||void 0)&&this.api.logClick(this.element)};
o6.prototype.onClick=function(a){if(g.YR(this.api.U())&&this.api.L("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var b=this.suggestion.Xk(),c={};g.kTa(this.api,c,"emb_rel_end");b=g.Ml(b,c);g.MU(b,this.api,a)}else g.LU(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
o6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};
o6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.U();this.B=a.If?!1:b.D};g.w(p6,i6);g.k=p6.prototype;g.k.create=function(){i6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.yq();this.B.T(this.player,"appresize",this.yq);this.B.T(this.player,"onVideoAreaChange",this.yq);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.B.T(this.player,"autonavchange",this.EL);this.B.T(this.player,"onAutonavCancelled",this.X1);a=this.videoData.autonavState;a!==this.Y&&this.EL(a);this.B.T(this.element,"transitionend",this.caa)};
g.k.destroy=function(){g.FC(this.B);g.ub(this.stills);this.stills=[];i6.prototype.destroy.call(this);g.Mu(this.element,"ytp-show-tiles");this.K.stop();this.Y=this.videoData.autonavState};
g.k.RC=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.Db;i6.prototype.show.call(this);g.Mu(this.element,"ytp-show-tiles");this.player.U().B?g.Eu(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.mU(this.player,!1);q6(this)?(r6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.DB():3===this.videoData.autonavState&&this.j.Sw()):(g.mU(this.player,!0),r6(this));a!==this.Db&&this.player.logVisibility(this.element,!0)};
g.k.hide=function(){var a=this.Db;i6.prototype.hide.call(this);this.j.Sw();r6(this);a!==this.Db&&this.player.logVisibility(this.element,!1)};
g.k.caa=function(a){a.target===this.element&&this.yq()};
g.k.yq=function(){var a,b,c,d;var e=(null==(a=this.videoData)?0:null==(b=a.suggestions)?0:b.length)?null==(c=this.videoData)?void 0:c.suggestions:[null==(d=this.videoData)?void 0:g.mT(d)];if(e.length){g.Ku(this.element,"ytp-endscreen-paginate");var f=this.J.Wk(!0,this.J.isFullscreen());if(a=g.fU(this.J))a=a.Wf()?48:32,f.width-=2*a;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;0<p&&(a<l||b<m);){var q=a/2,r=b/2,t=a<=l-2&&p>=r*n,u=b<=m-2&&p>=q*n;if((q+1)/r*d/h>h/(q/(r+1)*d)&&u)p-=q*n,b+=2;else if(t)p-=r*n,a+=2;else if(u)p-=q*n,b+=2;else break}d=!1;p>=3*n&&6>=c*n-p&&(4<=b||4<=a)&&(d=!0);n=96*a;p=54*b;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.fs(f,n,p);g.Wr(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.qG(g.mT(this.videoData));this.j instanceof
g6&&h6(this.j);g.Ou(this.element,"ytp-endscreen-takeover",q6(this));r6(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,t=0,d&&l>=a-2&&m>=b-2?t=1:0===m%2&&0===l%2&&(2>m&&2>l?0===m&&0===l&&(t=2):t=2),q=g.ke(q+this.C,c),0!==t){r=this.stills[h];r||(r=new o6(this.player),this.stills[h]=r,f.appendChild(r.element));u=Math.floor(p*m/b);var x=Math.floor(n*l/a),B=Math.floor(p*(m+t)/b)-u-4,F=Math.floor(n*(l+t)/a)-x-4;g.bs(r.element,x,u);g.fs(r.element,F,B);g.Wr(r.element,"transitionDelay",
(m+l)/20+"s");g.Ou(r.element,"ytp-videowall-still-mini",1===t);g.Ou(r.element,"ytp-videowall-still-large",2<t);t=Math.max(F,B);g.Ou(r.element,"ytp-videowall-still-round-large",256<=t);g.Ou(r.element,"ytp-videowall-still-round-medium",96<t&&256>t);g.Ou(r.element,"ytp-videowall-still-round-small",96>=t);q=e[q];r.suggestion!==q&&(r.suggestion=q,t=r.api.U(),u=g.Ju(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",e6(r,q,u),g.YR(t)&&!r.api.L("web_player_log_click_before_generating_ve_conversion_params")&&
(t=q.Xk(),u={},g.$T(r.api,"addEmbedsConversionTrackingParams",[u]),t=g.Ml(t,g.wP(u,"emb_rel_end")),r.updateValue("url",t)),(q=(q=q.sessionData)&&q.itct)&&r.api.setTrackingParams(r.element,q));h++}f.ariaBusy="false";g.Ou(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.of(a.element),g.rb(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.C=0,this.videoData=a,this.yq())};
g.k.Y1=function(){this.C+=this.stills.length;this.yq()};
g.k.Z1=function(){this.C-=this.stills.length;this.yq()};
g.k.JX=function(){return this.j.bl()};
g.k.EL=function(a){1===a?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.lq(),this.Db&&this.yq()):(this.G=!0,this.Db&&q6(this)&&(2===a?this.j.DB():3===a&&this.j.Sw()))};
g.k.X1=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.logVisibility(this.stills[a].element,!0);this.EL(1)}else this.D=null,this.G=!1;this.yq()};
g.k.xf=function(){return this.Db&&q6(this)};g.w(s6,i6);s6.prototype.ZD=function(){var a;return null==(a=this.j)?void 0:a.ZD()};
s6.prototype.show=function(){if(3!==this.player.getPlayerState()){i6.prototype.show.call(this);var a=this.B;if(a){var b=this.j.ZD();g.Ou(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.fU(this.player))||c.uu(!0);this.player.logVisibility(this.element,!0);this.watchButton.ac(!0)}};
s6.prototype.hide=function(){i6.prototype.hide.call(this);var a;null==(a=g.fU(this.player))||a.uu(!1);this.player.logVisibility(this.element,!1);this.watchButton.ac(!1)};g.w(Jqb,g.CV);g.k=Jqb.prototype;g.k.xu=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((g.pU(this.player)||this.B)&&!b)return!0;var c;var d=!!((null==a?0:g.mT(a))||(null==a?0:null==(c=a.suggestions)?0:c.length));d=!Gqb(this.player)||d;a=a.yj||g.fS(a.Ha);c=this.player.yD();return d&&!a&&!c&&!b};
g.k.xf=function(){return this.endScreen.xf()};
g.k.D7=function(){return this.xf()?this.endScreen.JX():!1};
g.k.xa=function(){this.player.jf("endscreen");g.CV.prototype.xa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.zb().oe.get("heartbeat"),d=g.mT(a);!d||b.videoId!==d.videoId||a.IS?(this.player.Jo(b.videoId,void 0,void 0,!0,!0,b),c&&c.ZI("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.CV.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.CV.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.xu()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){Iqb(this);this.D&&Hqb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new k6(this.player):this.endScreen=new p6(this.player),g.J(this,this.endScreen),g.sU(this.player,this.endScreen.element,4))};g.BV("endscreen",Jqb);})(_yt_player);
